project_id = "udxrzqpivtzunnfenmyd"

[functions.bkash-payment]
verify_jwt = false

[functions.session-expiry]
verify_jwt = false

[functions.customer-verify]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.nagad-payment]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.sms-receiver]
verify_jwt = false

[functions.backup-restore]
verify_jwt = false

[functions.send-email]
verify_jwt = false
