project_id = "udxrzqpivtzunnfenmyd"

[functions.bkash-payment]
verify_jwt = false

[functions.mikrotik-sync]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.bill-reminder]
verify_jwt = false

[functions.customer-login]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
