
-- Seed Divisions
INSERT INTO geo_divisions (name) VALUES ('Barishal') ON CONFLICT (name) DO NOTHING;
INSERT INTO geo_divisions (name) VALUES ('Chattogram') ON CONFLICT (name) DO NOTHING;
INSERT INTO geo_divisions (name) VALUES ('Dhaka') ON CONFLICT (name) DO NOTHING;
INSERT INTO geo_divisions (name) VALUES ('Khulna') ON CONFLICT (name) DO NOTHING;
INSERT INTO geo_divisions (name) VALUES ('Mymensingh') ON CONFLICT (name) DO NOTHING;
INSERT INTO geo_divisions (name) VALUES ('Rajshahi') ON CONFLICT (name) DO NOTHING;
INSERT INTO geo_divisions (name) VALUES ('Rangpur') ON CONFLICT (name) DO NOTHING;
INSERT INTO geo_divisions (name) VALUES ('Sylhet') ON CONFLICT (name) DO NOTHING;

-- Seed Districts
INSERT INTO geo_districts (division_id, name) SELECT id, 'Barguna' FROM geo_divisions WHERE name = 'Barishal' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Barishal' FROM geo_divisions WHERE name = 'Barishal' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Bhola' FROM geo_divisions WHERE name = 'Barishal' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Jhalokati' FROM geo_divisions WHERE name = 'Barishal' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Patuakhali' FROM geo_divisions WHERE name = 'Barishal' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Pirojpur' FROM geo_divisions WHERE name = 'Barishal' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Bandarban' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Brahmanbaria' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Chandpur' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Chattogram' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Comilla' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Cox''s Bazar' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Feni' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Khagrachhari' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Lakshmipur' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Noakhali' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Rangamati' FROM geo_divisions WHERE name = 'Chattogram' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Dhaka' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Faridpur' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Gazipur' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Gopalganj' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Kishoreganj' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Madaripur' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Manikganj' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Munshiganj' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Narayanganj' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Narsingdi' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Rajbari' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Shariatpur' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Tangail' FROM geo_divisions WHERE name = 'Dhaka' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Bagerhat' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Chuadanga' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Jessore' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Jhenaidah' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Khulna' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Kushtia' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Magura' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Meherpur' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Narail' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Satkhira' FROM geo_divisions WHERE name = 'Khulna' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Jamalpur' FROM geo_divisions WHERE name = 'Mymensingh' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Mymensingh' FROM geo_divisions WHERE name = 'Mymensingh' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Netrokona' FROM geo_divisions WHERE name = 'Mymensingh' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Sherpur' FROM geo_divisions WHERE name = 'Mymensingh' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Bogra' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Chapainawabganj' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Joypurhat' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Naogaon' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Natore' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Nawabganj' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Pabna' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Rajshahi' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Sirajganj' FROM geo_divisions WHERE name = 'Rajshahi' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Dinajpur' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Gaibandha' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Kurigram' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Lalmonirhat' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Nilphamari' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Panchagarh' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Rangpur' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Thakurgaon' FROM geo_divisions WHERE name = 'Rangpur' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Habiganj' FROM geo_divisions WHERE name = 'Sylhet' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Moulvibazar' FROM geo_divisions WHERE name = 'Sylhet' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Sunamganj' FROM geo_divisions WHERE name = 'Sylhet' ON CONFLICT (division_id, name) DO NOTHING;
INSERT INTO geo_districts (division_id, name) SELECT id, 'Sylhet' FROM geo_divisions WHERE name = 'Sylhet' ON CONFLICT (division_id, name) DO NOTHING;
